function [A_0] = b_plot(PSI, Nx, t, num, peakTime, q)

CO = [   0         0    1.0000; %BLUE
         0    0.5000         0; %GREEN
    1.0000         0         0; %RED
    0.5843    0.3882    0.3882; %BROWN
    0.7500         0    0.7500; %VIOLET
    0.0784    0.1686    0.5490; %NAVY
    0.2500    0.2500    0.2500;];%?

J = 2500;                                   % Scaling down of number of points
PSI_k = abs(fft(PSI'))/Nx;                  % Absolute normalized fft
data = log(PSI_k(1:num, 1:J:end));          % Our data

[tg, kg] = meshgrid(t, 1:num-1);

a = sqrt(8*q*(1-2*q));
alpha = sqrt(2*q)./cosh(a*(tg-peakTime));
alpha_2 = sqrt(2*q)./cosh(a*(t-peakTime));

A_0 = 1 - ((2*(1-2*q)+1i*a*tanh(a*(t-peakTime)))./sqrt(1-alpha_2.^2));
A_k = -(2*(1-2*q)+1i*a*tanh(a*(tg-peakTime)))./sqrt(1-alpha.^2).*((1-sqrt(1-alpha.^2))./alpha).^abs(kg);

figure
hFit = plot(t, log(abs([A_0; A_k])));
hold on
hData = plot(t(1:J:end), data); grid on;

for i=1:num
   set(hFit(i)                       , ...
        'Color'   , CO(i, :) );
    set(hData(i)                      , ...
        'Color'   , CO(i, :) );
end

% set(hFit                      , ...
%    'LineStyle'           , '-' , ...
%    'LineWidth'           , 1.5 );

set(hData                                , ...
    'LineStyle'           , 'none'       , ...
    'Marker'              , 'o'          , ...
    'MarkerSize'          , 6      );

%set(hData                      , ...
%   'LineStyle'           , '-' , ...
%   'LineWidth'           , 1.5 );

hXLabel = xlabel('t');
hYLabel = ylabel('log(|A_k|)');

%hLegend = legend( ...
%  [hFit, hData], ...
%  'Fit' , ...
%  'Numerical Data'      , ...
%  'location', 'SouthWest');

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel         ], ...
    'FontName'   , 'Helvetica');
%set([hLegend, gca]             , ...
%    'FontSize'   , 9           );
set([hXLabel, hYLabel       ]  , ...
    'FontSize'   , 10          );

set(gca, ...
  'Box'         , 'off'        , ...
  'TickDir'     , 'out'        , ...
  'TickLength'  , [.02 .02]    , ...
  'XMinorTick'  , 'off'         , ...
  'YMinorTick'  , 'off'         , ...
  'XGrid'       , 'on'         , ...
  'YGrid'       , 'on'         , ...
  'XColor'      , [.3 .3 .3]   , ...
  'YColor'      , [.3 .3 .3]   , ...
  'LineWidth'   , 1            , ...
  'YLim'        , [-40 5]      , ... 
  'XLim'        , [0 max(t)+t(2)]       , ...
  'XTick'       , [0:10:max(t)+t(2)]     );


end
